### ISSUE TITLE
This doesn't work!

### ISSUE THREAD

**Issue by macrael** [idlerun/simple-pex#2]
I checked out this git repo, started a venv and then:

```
$ pip wheel -w . .
$ pex --python=python3 -f $PWD requests myexample -e samplepkg.main -o samplepkg.pex
$ ./samplepkg.pex

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 128, in _get_module_details
    spec = importlib.util.find_spec(mod_name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'samplepkg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 365, in execute
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 408, in _execute
  File ".bootstrap/_pex/pex.py", line 466, in execute_entry
  File ".bootstrap/_pex/pex.py", line 471, in execute_module
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 201, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 134, in _get_module_details
    raise error(msg.format(mod_name, type(ex).__name__, ex)) from ex
ImportError: Error while finding module specification for 'samplepkg.main' (ModuleNotFoundError: No module named 'samplepkg')
```

**Comment by jeffjcrowe** [comment]
Two things to check:
- What shell are you using (bash, zsh, ..?) Just thinking whether the `$PWD` might not work everywhere
- I notice you are using `pip` directly. Did you note the version caveat [here](https://github.com/idlerun/simple-pex#python-version)? Worth trying that explicitly as `pip3` if you haven't to be confident it's using the right one

**Comment by macrael** [comment]
I am using bash, and I wrote everything inside of a venv created with
`python3 -m venv`, so my python versions should all be locked.

**Comment by jeffjcrowe** [comment]
Unfortunately I haven't used venv much. It doesn't seem to lock the `pip` version for me though, unless I'm mis-using it

```
➜  simple-pex git:(master) ✗ python3 -m venv .
➜  simple-pex git:(master) ✗ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

Try running `pip -V`?

**Comment by macrael** [comment]
you need to activate the venv before it takes effect. Try this:

> $ python3 -m venv venv # This creates a directory called venv in your
current directory
> $ source venv/bin/activate
> $ pip -V

**Comment by jeffjcrowe** [comment]
Ah there we go, thanks! Here's what I've got now

```
git clone https://github.com/idlerun/simple-pex.git ; \
cd simple-pex ; \
python3 -m venv venv ; \
source venv/bin/activate ; \
pip install wheel ; \
pip wheel -w . . ; \
pex --python=python3 -f $PWD requests myexample -e samplepkg.main -o samplepkg.pex ; \
./samplepkg.pex
```

This works OK for me (eventually just prints `HELLO WORLD!!`)

Not sure how best to figure out what the difference would be with your environment..

`pip -V` gives `pip 9.0.1 from ..../simple-pex/venv/lib/python3.5/site-packages (python 3.5)`
`python -V` gives `Python 3.5.1`

**Comment by idlerun** [comment]
Closing due to no reply and can't repro
